$schema: https://raw.githubusercontent.com/streetsidesoftware/cspell/main/cspell.schema.json
version: "0.2"
name: Neko Boi Nick's cSpell config
ignorePaths:
  - submodules
  - cspell.config.yaml
  - cspell.json
allowCompoundWords: true
dictionaries:
  - en_US
  - en-gb
  - companies
  - softwareTerms
  - misc
  - typescript
  - node
  - php
  - go
  - python
  - powershell
  - html
  - css
  - csharp
  - latex
  - bash
  - fonts
  - filetypes
words:
  - ACFAppWorkshop
  - aoba  # Name of a mod developer
  - ApiKey
  - AppWorkshop
  - aseprite  # A name of a common image editing softwar2e
  - brrainz  # Name of a mod developer
  - BuildID
  - Cascadia  # A name of a font
  - CPython
  - CreationFlags
  - DatabaseBuilder
  - Datas
  - DBBuilder  # Short for database builder
  - DescriptionByVersion
  - DescriptionsByVersion
  - dmypy  # Short for MyPy daemon
  - DocStrings
  - Encapsulator
  - Eustace  # Name of a developer
  - EventBus
  - ExceptHook
  - FollowLinks
  - ForceLoadAfter
  - ForceLoadBefore
  - GameVersion
  - gedit  # Name of a common text editor
  - GitPython
  - Hettiger  # Name of a developer
  - IncludeKVTags
  - IncompatibleWith
  - IncompatibleWithByVersion
  - IPublishedFileService
  - ISort
  - joseasoler  # The developer for Todds
  - krkr  # Name of a mod developer
  - Linq  # A common .NET namespace name.
  - LoadAfter
  - LoadAfterByVersion
  - LoadBefore
  - LoadBeforeByVersion
  - Ludeon
  - ModDependencies
  - ModDependenciesByVersion
  - ModMetadata
  - ModName
  - MSVC
  - MSVS
  - MSYS2
  - NatSort
  - NatSorted
  - ncipollo
  - NoFilter
  - NoInclude
  - NoKey
  - NoRecurseDirs
  - Nuitka
  - OnExc
  - oset  # Short for ordered set
  - PackageId
  - pfid
  - pfids
  - PlayerFaction
  - PsUtil
  - PublishedFileID
  - PublishedFileIDs
  - PyEnv
  - PyPa
  - PySide
  - pysqlite
  - pyvenv
  - pygtk
  - PyTestQt
  - QLabels
  - QObject
  - QtBot
  - QtWebEngine
  - Redist
  - Redistributables
  - Rentry
  - Repolish
  - Repolishing
  - RimSort
  - SaveDataFolder
  - SavedScenario
  - ScanDir
  - Scons
  - shfmt  # A common Python package
  - Sodipodi
  - SteamApps
  - SteamCMD
  - SteamDB
  - SteamWorks
  - Subfolders
  - SupportedVersions
  - taranchuk
  - TargetVersion
  - TimeTouched
  - TimeUpdated
  - Todds
  - TopDown
  - Topo
  - TopoLevels
  - TopoSort
  - Unhighlighting
  - Universum
  - Unpolish
  - Unposted
  - VirtualEnv
  - WebAPI
  - Zetrith  # Name of a mod feveloepr
ignoreRegExpList:
  - (?<=`)n\w+
  - (?<=-?-)\w+(?=-\w+)?
  - (?<=\.)icns
  - (?<=.)ipynb(?=_checkpoints)
  - ltex(?=\.dictionary\*)
  - (?<=:)rtype(?=:)
  - \bNeko(?= ?Boi ?Nick\b)|(?<=\bNeko ?)Boi(?= ?Nick\b)
  - (?<=(?<!\\)\])\w+
ignoreWords:
  - ccache
  - forgor # A silly wod (personal preference)
  - incomp # Short for incompatibility
  - unsub # Short for unsubscribe
  - xattr
  - signup
  - libxcb
  - qapp # Short for QApplication
  - testke
  - yayayay
